# resets
DG_ANSI_X='\033[0m' # No style
DG_ANSI_X_COL='\033[0;39m' # no color
DG_ANSI_X_BG='\033[0;49m' # no background

DG_ANSI_X_BOLD='\033[0;21m'
DG_ANSI_X_DIM='\033[0;22m'
DG_ANSI_X_UNDER='\033[0;24m'
DG_ANSI_X_BLINK='\033[0;25m'
DG_ANSI_X_INVERT='\033[0;27m'
DG_ANSI_X_PASS='\033[0;28m'

# basic format
DG_ANSI_BOLD='\033[0;1m'
DG_ANSI_DIM='\033[0;2m'
DG_ANSI_UNDER='\033[0;4m'
DG_ANSI_BLINK='\033[0;5m'
DG_ANSI_INVERT='\033[0;7m'
DG_ANSI_PASS='\033[0;8m'

# colors
DG_ANSI_DEF='\033[0;39m'
DG_ANSI_BLA='\033[0;30m'
DG_ANSI_RED='\033[0;31m'
DG_ANSI_GRE='\033[0;32m'
DG_ANSI_YEL='\033[0;33m'
DG_ANSI_BLU='\033[0;34m'
DG_ANSI_MAG='\033[0;35m'
DG_ANSI_CYA='\033[0;36m'
DG_ANSI_LGRA='\033[0;37m'
DG_ANSI_DGRA='\033[0;90m'
DG_ANSI_LRED='\033[0;91m'
DG_ANSI_LGRE='\033[0;92m'
DG_ANSI_LYEL='\033[0;93m'
DG_ANSI_LBLU='\033[0;94m'
DG_ANSI_LMAG='\033[0;95m'
DG_ANSI_LCYA='\033[0;96m'
DG_ANSI_WHI='\033[0;97m'

# backgrounds
DG_ANSI_BG_DEF='\033[0;49m'
DG_ANSI_BG_BLA='\033[0;40m'
DG_ANSI_BG_RED='\033[0;41m'
DG_ANSI_BG_GRE='\033[0;42m'
DG_ANSI_BG_YEL='\033[0;43m'
DG_ANSI_BG_BLU='\033[0;44m'
DG_ANSI_BG_MAG='\033[0;45m'
DG_ANSI_BG_CYA='\033[0;46m'
DG_ANSI_BG_LGRA='\033[0;47m'
DG_ANSI_BG_DGRA='\033[0;100m'
DG_ANSI_BG_LRED='\033[0;101m'
DG_ANSI_BG_LGRE='\033[0;102m'
DG_ANSI_BG_LYEL='\033[0;103m'
DG_ANSI_BG_LBLU='\033[0;104m'
DG_ANSI_BG_LMAG='\033[0;105m'
DG_ANSI_BG_LCYA='\033[0;106m'
DG_ANSI_BG_WHI='\033[0;107m'

# TODO: convert all icons to unicode https://unicode.org/emoji/charts/full-emoji-list.html


# icons
DG_ICON_MPIN='📍'
DG_ICON_SPARK='✨'
DG_ICON_WATCH='⏱️'
DG_ICON_SKULL='💀'
DG_ICON_SWATCH='⏱'
DG_ICON_BALLOON='🎈'
DG_ICON_ROCKET='🚀'
DG_ICON_GIFT='🎁'
DG_ICON_BOX='📦'
DG_ICON_WAND='🪄'
DG_ICON_SCROLL='📜'
DG_ICON_EYES='👀'
DG_ICON_BOOKMARK='🔖'
DG_ICON_SEEDLING='🌱'
DG_ICON_WHALE='🐳'
DG_ICON_ATOM='⚛️'
DG_ICON_RMAG='🔎'
DG_ICON_LMAG='🔍'
DG_ICON_GEM='💎'
DG_ICON_CONTROLS='🎛️'
DG_ICON_BOOKS='📚'
DG_ICON_BOOK_NOTE='📓'
DG_ICON_BOOK_ORA='📙'
DG_ICON_BOOK_GRE='📗'
DG_ICON_BOOK_YEL='📒'
DG_ICON_BOOK_BLU='📘'
DG_ICON_BOOK_RED='📕'
DG_ICON_BOOK_RAI='📑'
DG_ICON_STAR='⭐'
DG_ICON_GSTAR='🌟'
DG_ICON_CHECK='✔️'
DG_ICON_CHECKBOX='☑️'
DG_ICON_CHECKBOX_GRE='✅'
DG_ICON_PLUS='➕'
DG_ICON_RAILWAY='🛤️'

DG_ICON_MEDAL_MIL='🎖️'
DG_ICON_MEDAL_SPO='🏅'
DG_ICON_MEDAL_SPO_1='🥇'
DG_ICON_MEDAL_SPO_2='🥈'
DG_ICON_MEDAL_SPO_3='🥉'
DG_ICON_TROPHY='🏆'
DG_ICON_TOPHAT='🎩'

DG_ICON_LAPTOP='💻'
DG_ICON_DISK='💾'
DG_ICON_KEYBOARD='⌨️'
DG_ICON_TOOLBOX='🧰'
DG_ICON_TOOLS='🛠️'
DG_ICON_VICE='🗜️'
DG_ICON_GEAR='⚙️'
DG_ICON_ANCHOR='⚓'
DG_ICON_METRO='🚇'
DG_ICON_ABACUS='🧮'
DG_ICON_PUZZLE='🧩'
DG_ICON_FIRE='\U1F525'
DG_ICON_TESTTUBE='🧪'
DG_ICON_JOKER='🃏'
DG_ICON_SNAKE='🐍'
DG_ICON_RAISE='🙌'
DG_ICON_CLAP='👏'
DG_ICON_PINCH='🤏'
DG_ICON_FOLDERS='🗂️'
DG_ICON_CROSSMARK='❌'
DG_ICON_WARNING='⚠️ '
DG_ICON_TORNADO='🌪️'
DG_ICON_CIRCLE_GRE='🟢'
DG_ICON_SQUARE_RED='🟥'
DG_ICON_YARN='🧶'

DG_ICON_UNI_PUSH='\u2350'
DG_ICON_UNI_PULL='\u2357'
DG_ICON_UNI_GIT='\U1F536'
DG_ICON_UNI_PLUS='\U002B'


DG_ICON_UNI_BRANCH='\u2387 '
DG_ICON_UNI_KEYBOARD='\u2328'


# Terminal Tetris

# beginner
DG_TETRIS_REC='shape_rec'
DG_TETRIS_SQU='shape_squ'

# intermediate add in:
DG_TETRIS_LET_L='shape_l'
DG_TETRIS_LET_T='shape_t'

# advanced add in:
DG_TETRIS_LET_S='shape_s'
DG_TETRIS_LET_Z='shape_z'

# extreme add in:

DG_TETRIS_LET_A='shape_a'
DG_TETRIS_LET_B='shape_b'
DG_TETRIS_LET_C='shape_c'
DG_TETRIS_LET_D='shape_d'




